#ifndef __COMMON__
#define __COMMON__
#define DESC_TYPE_TX 1001
#define DESC_TYPE_RX 1002
#define QUEUE_FULL 1003
#define SUCCESS_OP 1004
#define DESC_COUNT 128
#define DESC_SIZE 16
#define MTU 1500
#define DEFAULT_TIMER 1000
#define QUEUE_OP_ENQUEUE 1001
#define QUEUE_OP_DEQUEUE 1002
#define QUEUE_FULL 1003
#define QUEUE_EMPTY 1004
#define QUEUE_OP_SUCCESS 1005
#define COPY_FROM_QUEUE 1
#define RES_NAME_REG_BASE "reg_base"
#define PLAT_DEVICE_NAME "net_plat_dev"

#define REG_MEM_SIZE 4096
#define TX_DESC_MEM (DESC_COUNT * DESC_SIZE)
#define RX_DESC_MEM (DESC_COUNT * DESC_SIZE)
#define TX_BUFFER_MEM (MTU * DESC_COUNT)
#define RX_BUFFER_MEM (MTU * DESC_COUNT)
#define TOTAL_MEM (TX_DESC_MEM + RX_DESC_MEM + TX_BUFFER_MEM + RX_BUFFER_MEM)
#define REG_OFFSET 0
#define TX_DESC_MEM_OFFSET 0//(REG_MEM_SIZE)
#define RX_DESC_MEM_OFFSET (TX_DESC_MEM_OFFSET + TX_DESC_MEM)
#define TX_BUFFER_OFFSET (RX_DESC_MEM_OFFSET + RX_DESC_MEM)
#define RX_BUFFER_OFFSET (TX_BUFFER_OFFSET + TX_BUFFER_MEM)
#define ETH_ALEN 6
#endif